apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental
  template:
    metadata:
      labels:
        app: rental
    spec:
      containers:
      - name: rental
        image: rental-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: SPRINGBOOT_URL
          value: http://storage-service:8080
        - name: RABBITMQ_URL
          value: amqp://rabbitmq:5672
---
apiVersion: v1
kind: Service
metadata:
  name: rental-service
spec:
  type: NodePort
  selector:
    app: rental
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
